// $ANTLR 2.7.6 (2005-12-22): "CALDoc.g" -> "CALDocLexer.java"$

// Package declaration
package org.openquark.cal.compiler;

public interface CALDocTokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int CALDOC_OPEN = 4;
	int CALDOC_CLOSE = 5;
	int CONS_ID = 6;
	int VAR_ID = 7;
	int ORDINAL_FIELD_NAME = 8;
	int EQUALS = 9;
	int COMMA = 10;
	int DOT = 11;
	int CALDOC_NEWLINE = 12;
	int CALDOC_WS = 13;
	int CALDOC_NEWLINE_WITH_LEADING_ASTERISK = 14;
	int CALDOC_NEWLINE_WITH_OPTIONAL_LEADING_ASTERISK_SPEC = 15;
	int CALDOC_NEWLINE_WITH_OPTIONAL_LEADING_ASTERISK = 16;
	int CALDOC_IGNORED_DOC_WS = 17;
	int CALDOC_SEE_TAG_FUNCTION_CONTEXT = 18;
	int CALDOC_SEE_TAG_MODULE_CONTEXT = 19;
	int CALDOC_SEE_TAG_DATACONS_CONTEXT = 20;
	int CALDOC_SEE_TAG_TYPECONS_CONTEXT = 21;
	int CALDOC_SEE_TAG_TYPECLASS_CONTEXT = 22;
	int CALDOC_SEE_TAG_CONTEXT = 23;
	int CALDOC_SEE_TAG_CONS_ID = 24;
	int CALDOC_SEE_TAG_VAR_ID = 25;
	int CALDOC_SEE_TAG_QUOTE = 26;
	int CALDOC_SEE_TAG_EQUALS = 27;
	int CALDOC_SEE_TAG_COMMA = 28;
	int CALDOC_SEE_TAG_DOT = 29;
	int CALDOC_AUTHOR_TAG = 30;
	int CALDOC_DEPRECATED_TAG = 31;
	int CALDOC_RETURN_TAG = 32;
	int CALDOC_VERSION_TAG = 33;
	int CALDOC_ARG_TAG = 34;
	int CALDOC_ARG_TAG_VAR_ID = 35;
	int CALDOC_ARG_TAG_ORDINAL_FIELD_NAME = 36;
	int CALDOC_SEE_TAG = 37;
	int CALDOC_OPEN_INLINE_TAG = 38;
	int CALDOC_CLOSE_INLINE_TAG = 39;
	int CALDOC_INLINE_SUMMARY_TAG = 40;
	int CALDOC_INLINE_EM_TAG = 41;
	int CALDOC_INLINE_STRONG_TAG = 42;
	int CALDOC_INLINE_SUP_TAG = 43;
	int CALDOC_INLINE_SUB_TAG = 44;
	int CALDOC_INLINE_UNORDERED_LIST_TAG = 45;
	int CALDOC_INLINE_ORDERED_LIST_TAG = 46;
	int CALDOC_INLINE_ITEM_TAG = 47;
	int CALDOC_INLINE_CODE_TAG = 48;
	int CALDOC_INLINE_URL_TAG = 49;
	int CALDOC_INLINE_LINK_TAG = 50;
	int CALDOC_INLINE_TAG = 51;
	int CALDOC_INLINE_UNKNOWN_TAG = 52;
	int CALDOC_UNKNOWN_TAG = 53;
	int CALDOC_SEE_TAG_UNKNOWN_CONTEXT = 54;
	int CALDOC_SEE_TAG_UNKNOWN_REFERENCE = 55;
	int CALDOC_REGULAR_TEXT_LINE = 56;
	int CALDOC_BLANK_TEXT_LINE = 57;
	int CALDOC_TEXT_LINE = 58;
}
